baseurl = "joedotson2.com/"
title = "Joe Dotson"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Joseph R Dotson II"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Author]

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Joe Dotson"
    description = "Adventures in Analytics, Politics, & Life"
    github = "https://github.com/joedotson2"
    gitlab = "https://gitlab.com/joedotson2"
    linkedin = "https://www.linkedin.com/in/joedotson2/"
    twitter = "https://twitter.com/JoeDot2"
    email = "joe@joedotson2.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
